### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by radar** [paypal/adaptivepayments-sdk-ruby#18]
The current version of this gem on RubyGems uses paypal-sdk-core ~> 0.2.3: 

![screen shot 2015-02-16 at 2 14 48 pm](https://cloud.githubusercontent.com/assets/2687/6206796/30d55798-b5e6-11e4-805d-64d041fb1d1d.png)

However the dependency on paypal-sdk-permissions is `~> 0.3.0`.

Releasing a new version of this gem would include [this commit](https://github.com/paypal/adaptivepayments-sdk-ruby/commit/3c195f91cded28efc7b9ccbeeede87916d1a54df) which would correct the dependency.

**Comment by AW-UC** [comment]
That commit is from September 2014 and still no new release? Wow! Just like the rest of Paypal's SDKs and APIs: Not much happening over the past 2 years. Going to be dropped in favor a Braintree API?

**Comment by juwlee** [comment]
[New gem](https://rubygems.org/gems/paypal-sdk-adaptivepayments/versions/1.117.1) has been released with the dependency update.
