### ISSUE TITLE
Paypal Echeck not working

### ISSUE THREAD

**Issue by laxmanmore** [paypal/adaptivepayments-sdk-ruby#19]
I want paypal echeck as defaults payment method,

:fundingConstraint => {
                                :allowedFundingType => {
                                :fundingTypeInfo => [{
                                  :fundingType => "ECHECK"
                                }]
                              }
                            }

Still it is allowing paypal balance method, And users can able to change method from pay time So i dont want to users should change payment method.

**Comment by tomwhipple** [comment]
A key feature of PayPal is that users can pay in the way that is most convenient for them.
