### ISSUE TITLE
Load error

### ISSUE THREAD

**Issue by newom** [paypal/adaptivepayments-sdk-ruby#26]
I'm new and this is probably a very new-be issue with API.  In any event,

I have followed the install and config instructions, but my application cannot load the 'paypal-sdk-adaptivepayments' file at the require step.  Can some one help?

Thanks.

**Comment by newom** [comment]
I resolved the issue by resetting the rails server, but I remain interested as to why that was the solution.  I am guessing that the server loads all the libraries when it starts?

**Comment by pp-randy** [comment]
@newom this seems to be the case when adding or removing gems. I'm not a ruby on rails guy but found some information here: http://stackoverflow.com/questions/17729345/when-do-i-need-to-restart-server-in-rails
