### ISSUE TITLE
ipnNotificationUrl not sending any IPN requests

### ISSUE THREAD

**Issue by Sexual** [paypal/adaptivepayments-sdk-ruby#34]
### General information

* SDK/Library version: Latest
* Environment: Only tested in sandbox
* Language, language version, and OS:  Ruby 2.4.0 Rails 5.0.2

### Issue description

When using the below code, the payment is created correctly, but we do not receive IPN requests to the URL specified. And yes, the IPN url is correct and reachable. 

``` ruby
    pay = paypal.build_pay(
      actionType: 'PAY',
      cancelUrl: 'https://VALIDDOMAINHEREBUTREMOVED/p/7b84a62b',
      currencyCode: paypal_params[:currency],
      feesPayer: 'PRIMARYRECEIVER',
      ipnNotificationUrl: 'https://VALIDDOMAINHEREBUTREMOVED/payments/paypal',
      receiverList: {
        receiver: [
          { email: 'seller@example.com', amount: price, primary: true, invoiceId: paypal_params[:order_id] },
          { email: 'fees@example.com', amount: sfee, invoiceId: paypal_params[:order_id] }
        ]
      },
      returnUrl: 'https://VALIDDOMAINHEREBUTREMOVED/p/7b84a62b'
    )
```

**Comment by pp-randy** [comment]
Do you have a correlation id from the API response you can share?  The field itself looks correct to me.

**Comment by Sexual** [comment]
@pp-randy `2182a21d5619e`

**Comment by pp-randy** [comment]
Did the IPN show up for you from that last one?  I got a significant delay trying to reproduce but see that I did get it finally.

**Comment by Sexual** [comment]
@pp-randy I'm not sure as I had closed down the Ngrok tunnel whilst I was away. Want me to create a new one and test it?

Are you able to get on Gitter so we can test this without filling up the issues?

**Comment by Sexual** [comment]
@pp-randy Just had another attempt, no luck receiving the IPN request.

**Comment by pp-randy** [comment]
Does your Ngrok tunnel work with the IPN Simulator?  
 https://developer.paypal.com/developer/ipnSimulator/

I got my last IPN without a delay, so at least the delay has cleared up.

**Comment by Sexual** [comment]
@pp-randy 

Just submitted an order at 2017-03-27 19:40:53 UTC

Yet to receive the IPN request. Are these delays just due to the sandbox?

Correlation ID `6e9413e65582`

**Comment by pp-randy** [comment]
Can you enable IPN on your API Caller account?  https://www.sandbox.paypal.com/us/cgi-bin/webscr?cmd=_profile-ipn-notify

This should help me get access to the IPN history by looking at your API Caller logs further.  If you would enable it then run a test or two I would appreciate it.

**Comment by Sexual** [comment]
I seem to have gotten it working. Tried creating a new API user for the "fee" account and it's working fine now.

**Comment by pp-randy** [comment]
Thats great.  Let me know if you need further help.
