### ISSUE TITLE
Delayed Chained Payments

### ISSUE THREAD

**Issue by jgujgu** [paypal/adaptivepayments-sdk-ruby#35]
Hello,

I was wondering how easy/hard it is to perform Delayed Chained Payments with the SDK as it is, because it's been hard for me to find examples of them generally and I haven't found any mention of them in the code base. How would you suggest to perform them?

-Jeffrey

**Comment by xiaoleih41** [comment]
PayPal has deprecated adaptive payment API. Depending on your specific user case, you may look into [PayPal marketplace product](https://developer.paypal.com/docs/marketplaces/pp4mp/). I will highly recommend you to contact the customer service number listed on  your account, request to talk to a sales person. The assigned sales rep should be able to give you the best recommendations on the product which fits your specific business need and coordinate necessary integration assistant resources to help you with any technical questions.

**Comment by xiaoleih41** [comment]
Close the issue as the answer has been provided
