### ISSUE TITLE
Float class can unexpectedly cause error

### ISSUE THREAD

**Issue by mattnish** [paypal/adaptivepayments-sdk-ruby#36]
### General information

* SDK/Library version: 1.117.1
* Environment: Sandbox and Production
* Error ID: 589023
* Language, language version, and OS: ruby 2.4.2p198

### Issue description

Float values in ruby are sometimes inaccurate, creating fractional decimal amounts unexpectedly.

Example: `2.20 - 2.01 = 0.1900000000000004`

This gem uses the dependency `sdk-core-ruby`, which has a class `Float` (simply returning `float.to_f`).  Because it's using floats instead of decimals or integers, this gem's `build_pay` method can randomly fail as it takes an `amount` parameter and adds extra fractional amounts.

### To Reproduce

To experience this, try using `715.57` as the `amount` parameter for `build_pay` and it will return an error `589023 : If the fractional amount is rounded for currency conversion, funds could be lost`, despite the parameter being correct.  Looking at the logs, the gem tries to send `715.57000000001` to the api.

### Monkey Patching

To fix this in my app for now, I've overwritten the `sdk-core-ruby` `Float` class using `BigDecimal`.  I would love to know if this is safe in your opinion, though, and if the use of float over decimal was intentional.

```
module PayPal::SDK::Core
  module API
    module DataTypes
      module SimpleTypes
        class Float < ::Float
          def self.new(float)
            # Floats are inaccurate. BigDecimal is better.
            # To support currencies with up to 4 subunits, we round(4)
            BigDecimal.new(float.to_f.round(4).to_s)
          end
        end
      end
    end
  end
end
```

**More info on float problems with money:**

Reference 1: https://stackoverflow.com/a/3730040/1109211

Reference 2: https://stackoverflow.com/a/3730249/1109211

**Comment by xiaoleih41** [comment]
Adaptive API has been deprecated. Please advise the reason that you are using this SDK and hopefully we can find you a newer and updated API to support your integration.

**Comment by mattnish** [comment]
Hey @xiaoleih41 thanks for the response.  We've been using it the last 2 years for marketplace-style payments.  We use the API to generate a payment link to the payee, which opens a new page on PayPal for the payer.  The payer can pay via credit card or their PayPal account, then is redirected back to our app upon completion.

Is there a newer API that supports the same functionality, or similar in that 2 users can pay/receive money with PayPal accounts?

**Comment by xiaoleih41** [comment]
It looks like you are already in production. I will not suggest you to change integration if you don't have to. Please consider to submit a pull request on the SDK and we will be happy to review.

**Comment by Jelkster** [comment]
@xiaoleih41 can you please recommend what APIs should be used for new applications being built that depend on interactions described by @mattnish aka marketplace/2 users can pay AND receive money with PayPal.

**Comment by xiaoleih41** [comment]
https://developer.paypal.com/docs/marketplaces/pp4mp/ will be the new product if it's a chained payment type of situation. If you are just wanting to direct payment to a 3rd party,  You can consider to use [payee](https://developer.paypal.com/docs/api/payments/#definition-cart) object to specify the 3rd party receiver in the REST API.

**Comment by xiaoleih41** [comment]
Close this issue has the solution has been provided.
